#!/bin/bash

set -ue

DIR="$1"
shift

if [ ! -d "$DIR" ]; then
  echo "usage: $(basename "$0") directory command"
  exit 1
fi


find "$DIR" -mindepth 1 -maxdepth 1 -type d | while read -r d; do
  echo "$d"
  pushd "$d" > /dev/null
  eval "$@"
  popd > /dev/null
done
